### ISSUE TITLE
Agents of Edgewatch integration please

### ISSUE THREAD

**Issue by Alexander-HPA** [deidril/pf2-pdf-en-import#18]
Hi,

First I want to thank you for investing your time into this. 
Could you please integrate support for the Agents of Edgewatch PDFs? I would greatly appreciate it. 

Cheers

**Comment by deidril** [comment]
Hi,

Thanks for your message :)

AoE is a very good campaign. I'm currently running it (we just completed book 2), and yes, i would like to integrate the support for AoE. 

However:

- I don't have the english pdf, I have the translated hardcover books. It would cost 120$ to get them. 

- A single AP book is around 1.5 to 2 weeks of work. So that's about 9  to 12 weeks for the whole campaign. I have to reduce greatly the time needed for an AP book before doing this. Once i completed a list of tools, maybe i will import AP. But i will surely start with Strength of Thousand since i have the PDFs for that one. ( thanks Humble Bundle ... )

There is a FAQ on the pathfinder foundry discord about importing Agents with a foundry v9 version and the pdf2foundry module,  then migrate the world to v10. I fear i can't do nothing more than giving you this advice at this current time. 

Things may be different in a few months ...

**Comment by deidril** [comment]
pdf2foundry has been imported to v10 and support agents of edgewatch
