### ISSUE TITLE
early PFS AP's

### ISSUE THREAD

**Issue by Pinktiger74** [deidril/pf2-pdf-en-import#19]
Saw that you also doing the new PFS AP's
Since I mix these in long AP's for my players I was wondering if you also are planning to do those of season 1 and 2.

Also I am wondering how difficult it is to make a pdf to foundry AP? Maybe I could help (probably over a long time)

**Comment by deidril** [comment]
Hello, 

I've no short plan to do import of pdf covered by pdf2foundry, simply because i don't have these pdfs and also because the time to make an import is still too much to import the new stuff and also the old stuff. 

I spend half of the time improving the import process, and so far i halved the time when i consider my first import in July. I still have to improve this to consider import old stuff, but i'm confident about it.

The best way people could help imports is by doing high quality map modules, like narchy's modules. Doing the maps with wall is certainly on of the biggest time sink when readying an import.

Unfortunaly, i don't have also any tools or time to teach people how to do an import. I've been considering this since a long time, and it's one of my long term plans. But it's far away from now ...

**Comment by Pinktiger74** [comment]
I started to remake the maps in dungeon alchemist importing them in foundry and then set up the walls and such. First because I don't have the mappacks usually, only have those of 2 humble bundles and a few extra. Secondly because I like them more then old school maps. 
Not sure if that is ok for you to work with. 
If it is then glad to play these through to you for the pfs AP's I have and do. (Almost finished all for the follow up otari AP and first pfs 1.1

**Comment by deidril** [comment]
Sure for PFS1.1. You could publish your own module with your maps or i'll join them with my module along a license of your choice. I'll not do the otari AP since i guess it's the beginner box content, which is already covered by a premium module.

**Comment by Pinktiger74** [comment]
So far I only helped on the gm screen clean up. So will have to figure out how to create a module first 😄 
But once I figure that out I will let you know. 
Also big thanks on the work you already done so far, it looks great.

**Comment by deidril** [comment]
hi, pdf2foundry has been updated to v10 and support early pfs adventures. :)
